import java.sql.*;
import java.awt.Color;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Sandun Siwantha
 */
public class Oders extends javax.swing.JFrame {

    /**
     * Creates new form Oders
     */
    public Oders() {
        initComponents();
        this.setLocationRelativeTo(this);
    }
       /** Connection con;
        Statement st;
        ResultSet rs;*/
        

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        grTotal = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextField11 = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        BILL_TABLE_ = new javax.swing.JTable();
        jLabel17 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jTextField12 = new javax.swing.JTextField();
        jTextField24 = new javax.swing.JTextField();
        jTextField25 = new javax.swing.JTextField();
        jLabel43 = new javax.swing.JLabel();
        exit = new javax.swing.JLabel();
        back2 = new javax.swing.JLabel();
        clear = new javax.swing.JLabel();
        jTextField17 = new javax.swing.JTextField();
        jLabel30 = new javax.swing.JLabel();
        reset2 = new javax.swing.JLabel();
        total = new javax.swing.JLabel();
        jTextField23 = new javax.swing.JTextField();
        DessertBoder = new javax.swing.JPanel();
        jCheckBox19 = new javax.swing.JCheckBox();
        jCheckBox20 = new javax.swing.JCheckBox();
        jCheckBox21 = new javax.swing.JCheckBox();
        jCheckBox22 = new javax.swing.JCheckBox();
        jLabel45 = new javax.swing.JLabel();
        jLabel46 = new javax.swing.JLabel();
        jLabel47 = new javax.swing.JLabel();
        jLabel48 = new javax.swing.JLabel();
        jTextField19 = new javax.swing.JTextField();
        jTextField20 = new javax.swing.JTextField();
        jTextField21 = new javax.swing.JTextField();
        jTextField22 = new javax.swing.JTextField();
        jLabel51 = new javax.swing.JLabel();
        jLabel52 = new javax.swing.JLabel();
        jLabel53 = new javax.swing.JLabel();
        jLabel54 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        BeveragesBoder = new javax.swing.JPanel();
        jCheckBox13 = new javax.swing.JCheckBox();
        jCheckBox14 = new javax.swing.JCheckBox();
        jCheckBox15 = new javax.swing.JCheckBox();
        jCheckBox16 = new javax.swing.JCheckBox();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jTextField13 = new javax.swing.JTextField();
        jTextField14 = new javax.swing.JTextField();
        jTextField15 = new javax.swing.JTextField();
        jTextField16 = new javax.swing.JTextField();
        jLabel38 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        BurgerBoder = new javax.swing.JPanel();
        jCheckBox1 = new javax.swing.JCheckBox();
        jCheckBox2 = new javax.swing.JCheckBox();
        jCheckBox3 = new javax.swing.JCheckBox();
        jCheckBox4 = new javax.swing.JCheckBox();
        jCheckBox5 = new javax.swing.JCheckBox();
        jCheckBox6 = new javax.swing.JCheckBox();
        jLabel14 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        burgerBoder = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        AppetizerBoder = new javax.swing.JPanel();
        jCheckBox7 = new javax.swing.JCheckBox();
        jCheckBox8 = new javax.swing.JCheckBox();
        jCheckBox9 = new javax.swing.JCheckBox();
        jCheckBox10 = new javax.swing.JCheckBox();
        jCheckBox11 = new javax.swing.JCheckBox();
        jTextField18 = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jTextField7 = new javax.swing.JTextField();
        jTextField8 = new javax.swing.JTextField();
        jTextField9 = new javax.swing.JTextField();
        jTextField10 = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setPreferredSize(new java.awt.Dimension(1080, 720));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        grTotal.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        grTotal.setForeground(new java.awt.Color(246, 166, 0));
        grTotal.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        grTotal.setText("GRAND TOTAL");
        grTotal.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        grTotal.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        grTotal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                grTotalMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                grTotalMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                grTotalMouseExited(evt);
            }
        });
        jPanel1.add(grTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 590, 100, 30));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(246, 166, 0));
        jLabel3.setText("Cust_Id :");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, 70, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(246, 166, 0));
        jLabel4.setText("Date :");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(112, 6, 50, -1));

        jTextField11.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTextField11.setForeground(new java.awt.Color(246, 166, 0));
        jTextField11.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField11.setText("00");
        jPanel1.add(jTextField11, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 540, 50, 30));

        jPanel2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 153), 4, true));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BILL_TABLE_.setForeground(new java.awt.Color(246, 166, 0));
        BILL_TABLE_.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Item_Id", "Item_Name", "Price", "Quantity", "Amount"
            }
        ));
        jScrollPane1.setViewportView(BILL_TABLE_);
        if (BILL_TABLE_.getColumnModel().getColumnCount() > 0) {
            BILL_TABLE_.getColumnModel().getColumn(0).setHeaderValue("Item_Id");
            BILL_TABLE_.getColumnModel().getColumn(1).setHeaderValue("Item_Name");
            BILL_TABLE_.getColumnModel().getColumn(2).setHeaderValue("Price");
            BILL_TABLE_.getColumnModel().getColumn(3).setHeaderValue("Quantity");
            BILL_TABLE_.getColumnModel().getColumn(4).setHeaderValue("Amount");
        }

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 400, 290));

        jLabel17.setFont(new java.awt.Font("STXingkai", 1, 48)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(246, 166, 0));
        jLabel17.setText("Mr. Burger");
        jPanel2.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 10, 220, 90));

        jLabel23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/logo 3.png"))); // NOI18N
        jPanel2.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 400, 110, -1));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(246, 166, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setText("GRAND TOTAL :");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 470, 150, -1));

        jLabel31.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel31.setForeground(new java.awt.Color(246, 166, 0));
        jLabel31.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel31.setText("SUB TOTAL :");
        jPanel2.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 410, 140, -1));

        jLabel36.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel36.setForeground(new java.awt.Color(246, 166, 0));
        jLabel36.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel36.setText("DISCOUNT :");
        jPanel2.add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 440, 140, -1));
        jPanel2.add(jTextField12, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 470, 90, -1));
        jPanel2.add(jTextField24, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 410, 90, -1));
        jPanel2.add(jTextField25, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 440, 90, -1));

        jLabel43.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel43.setForeground(new java.awt.Color(246, 166, 0));
        jLabel43.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel43.setText("THANK YOU COME AGAIN!!");
        jPanel2.add(jLabel43, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 520, 230, 40));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 60, 440, 570));

        exit.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        exit.setForeground(new java.awt.Color(246, 166, 0));
        exit.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        exit.setText("EXIT");
        exit.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        exit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exitMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                exitMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                exitMouseExited(evt);
            }
        });
        jPanel1.add(exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 650, 100, 43));

        back2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        back2.setForeground(new java.awt.Color(246, 166, 0));
        back2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        back2.setText("SAVE");
        back2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        back2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        back2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                back2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                back2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                back2MouseExited(evt);
            }
        });
        jPanel1.add(back2, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 650, 100, 43));

        clear.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        clear.setForeground(new java.awt.Color(246, 166, 0));
        clear.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        clear.setText("CLEAR");
        clear.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        clear.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        clear.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                clearMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                clearMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                clearMouseExited(evt);
            }
        });
        jPanel1.add(clear, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 650, 100, 43));

        jTextField17.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTextField17.setForeground(new java.awt.Color(246, 166, 0));
        jPanel1.add(jTextField17, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 590, 100, 30));

        jLabel30.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(246, 166, 0));
        jLabel30.setText("DISCOUNT");
        jPanel1.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 540, 120, 30));

        reset2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        reset2.setForeground(new java.awt.Color(246, 166, 0));
        reset2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        reset2.setText("RESET");
        reset2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        reset2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        reset2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                reset2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                reset2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                reset2MouseExited(evt);
            }
        });
        jPanel1.add(reset2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 590, 70, 30));

        total.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        total.setText("TOTAL");
        total.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        total.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        total.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                totalMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                totalMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                totalMouseExited(evt);
            }
        });
        jPanel1.add(total, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 460, 80, 30));
        jPanel1.add(jTextField23, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 460, 100, 30));

        DessertBoder.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jCheckBox19.setText("Soft Drinks");
        jCheckBox19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox19ActionPerformed(evt);
            }
        });
        DessertBoder.add(jCheckBox19, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 58, -1, -1));

        jCheckBox20.setText("Chocolate Milkshake");
        jCheckBox20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox20ActionPerformed(evt);
            }
        });
        DessertBoder.add(jCheckBox20, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 86, -1, -1));

        jCheckBox21.setText("Faluda");
        jCheckBox21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox21ActionPerformed(evt);
            }
        });
        DessertBoder.add(jCheckBox21, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 114, -1, -1));

        jCheckBox22.setText("Passion");
        jCheckBox22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox22ActionPerformed(evt);
            }
        });
        DessertBoder.add(jCheckBox22, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 142, -1, -1));

        jLabel45.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel45.setText("-");
        jLabel45.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabel45.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel45MouseClicked(evt);
            }
        });
        DessertBoder.add(jLabel45, new org.netbeans.lib.awtextra.AbsoluteConstraints(174, 141, 14, 22));

        jLabel46.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel46.setText("-");
        jLabel46.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabel46.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel46MouseClicked(evt);
            }
        });
        DessertBoder.add(jLabel46, new org.netbeans.lib.awtextra.AbsoluteConstraints(174, 113, 14, 22));

        jLabel47.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel47.setText("-");
        jLabel47.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabel47.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel47MouseClicked(evt);
            }
        });
        DessertBoder.add(jLabel47, new org.netbeans.lib.awtextra.AbsoluteConstraints(174, 85, 14, 22));

        jLabel48.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel48.setText("-");
        jLabel48.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabel48.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel48MouseClicked(evt);
            }
        });
        DessertBoder.add(jLabel48, new org.netbeans.lib.awtextra.AbsoluteConstraints(174, 57, 14, 22));

        jTextField19.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField19.setText("00");
        DessertBoder.add(jTextField19, new org.netbeans.lib.awtextra.AbsoluteConstraints(194, 57, 31, -1));

        jTextField20.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField20.setText("00");
        DessertBoder.add(jTextField20, new org.netbeans.lib.awtextra.AbsoluteConstraints(194, 85, 31, -1));

        jTextField21.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField21.setText("00");
        DessertBoder.add(jTextField21, new org.netbeans.lib.awtextra.AbsoluteConstraints(194, 113, 31, -1));

        jTextField22.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField22.setText("00");
        DessertBoder.add(jTextField22, new org.netbeans.lib.awtextra.AbsoluteConstraints(194, 141, 31, -1));

        jLabel51.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel51.setText("+");
        jLabel51.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabel51.setPreferredSize(new java.awt.Dimension(8, 16));
        DessertBoder.add(jLabel51, new org.netbeans.lib.awtextra.AbsoluteConstraints(231, 141, 14, 22));

        jLabel52.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel52.setText("+");
        jLabel52.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabel52.setPreferredSize(new java.awt.Dimension(8, 16));
        DessertBoder.add(jLabel52, new org.netbeans.lib.awtextra.AbsoluteConstraints(231, 113, 14, 22));

        jLabel53.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel53.setText("+");
        jLabel53.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabel53.setPreferredSize(new java.awt.Dimension(8, 16));
        DessertBoder.add(jLabel53, new org.netbeans.lib.awtextra.AbsoluteConstraints(231, 85, 14, 22));

        jLabel54.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel54.setText("+");
        jLabel54.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabel54.setPreferredSize(new java.awt.Dimension(8, 16));
        DessertBoder.add(jLabel54, new org.netbeans.lib.awtextra.AbsoluteConstraints(231, 57, 14, 22));

        jLabel29.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel29.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "DESSERTS", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Segoe UI", 1, 18))); // NOI18N
        DessertBoder.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 27, 240, 150));

        jPanel1.add(DessertBoder, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 60, 280, 210));

        BeveragesBoder.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jCheckBox13.setText("Cheese Cake");
        jCheckBox13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox13ActionPerformed(evt);
            }
        });
        BeveragesBoder.add(jCheckBox13, new org.netbeans.lib.awtextra.AbsoluteConstraints(27, 38, -1, -1));

        jCheckBox14.setText("Chocolate Cupcake");
        jCheckBox14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox14ActionPerformed(evt);
            }
        });
        BeveragesBoder.add(jCheckBox14, new org.netbeans.lib.awtextra.AbsoluteConstraints(27, 68, -1, -1));

        jCheckBox15.setText("Lava Cake");
        jCheckBox15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox15ActionPerformed(evt);
            }
        });
        BeveragesBoder.add(jCheckBox15, new org.netbeans.lib.awtextra.AbsoluteConstraints(27, 98, -1, -1));

        jCheckBox16.setText("Honey Waffle");
        jCheckBox16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox16ActionPerformed(evt);
            }
        });
        BeveragesBoder.add(jCheckBox16, new org.netbeans.lib.awtextra.AbsoluteConstraints(27, 128, -1, -1));

        jLabel32.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel32.setText("-");
        jLabel32.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabel32.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel32MouseClicked(evt);
            }
        });
        BeveragesBoder.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(177, 128, 14, 22));

        jLabel33.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel33.setText("-");
        jLabel33.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabel33.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel33MouseClicked(evt);
            }
        });
        BeveragesBoder.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(177, 98, 14, 22));

        jLabel34.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel34.setText("-");
        jLabel34.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabel34.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel34MouseClicked(evt);
            }
        });
        BeveragesBoder.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(177, 68, 14, 22));

        jLabel35.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel35.setText("-");
        jLabel35.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabel35.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel35MouseClicked(evt);
            }
        });
        BeveragesBoder.add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(177, 38, 14, 22));

        jTextField13.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField13.setText("00");
        BeveragesBoder.add(jTextField13, new org.netbeans.lib.awtextra.AbsoluteConstraints(197, 38, 31, -1));

        jTextField14.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField14.setText("00");
        BeveragesBoder.add(jTextField14, new org.netbeans.lib.awtextra.AbsoluteConstraints(197, 68, 31, -1));

        jTextField15.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField15.setText("00");
        BeveragesBoder.add(jTextField15, new org.netbeans.lib.awtextra.AbsoluteConstraints(197, 98, 31, -1));

        jTextField16.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField16.setText("00");
        BeveragesBoder.add(jTextField16, new org.netbeans.lib.awtextra.AbsoluteConstraints(197, 128, 31, -1));

        jLabel38.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel38.setText("+");
        jLabel38.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabel38.setPreferredSize(new java.awt.Dimension(8, 16));
        BeveragesBoder.add(jLabel38, new org.netbeans.lib.awtextra.AbsoluteConstraints(237, 128, 14, 22));

        jLabel39.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel39.setText("+");
        jLabel39.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabel39.setPreferredSize(new java.awt.Dimension(8, 16));
        BeveragesBoder.add(jLabel39, new org.netbeans.lib.awtextra.AbsoluteConstraints(237, 98, 14, 22));

        jLabel40.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel40.setText("+");
        jLabel40.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabel40.setPreferredSize(new java.awt.Dimension(8, 16));
        BeveragesBoder.add(jLabel40, new org.netbeans.lib.awtextra.AbsoluteConstraints(237, 68, 14, 22));

        jLabel41.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel41.setText("+");
        jLabel41.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabel41.setPreferredSize(new java.awt.Dimension(8, 16));
        BeveragesBoder.add(jLabel41, new org.netbeans.lib.awtextra.AbsoluteConstraints(237, 38, 14, 22));

        jLabel42.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel42.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "BEVERAGES", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Segoe UI", 1, 18))); // NOI18N
        BeveragesBoder.add(jLabel42, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 240, 160));

        jPanel1.add(BeveragesBoder, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 270, 280, 230));

        BurgerBoder.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jCheckBox1.setText("Chicken Burger");
        jCheckBox1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jCheckBox1MouseClicked(evt);
            }
        });
        jCheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox1ActionPerformed(evt);
            }
        });
        BurgerBoder.add(jCheckBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(35, 49, -1, -1));

        jCheckBox2.setText("Beef Burger");
        jCheckBox2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jCheckBox2MouseClicked(evt);
            }
        });
        jCheckBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox2ActionPerformed(evt);
            }
        });
        BurgerBoder.add(jCheckBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(35, 77, -1, -1));

        jCheckBox3.setText("Crispy Chicken Burger");
        jCheckBox3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jCheckBox3MouseClicked(evt);
            }
        });
        jCheckBox3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox3ActionPerformed(evt);
            }
        });
        BurgerBoder.add(jCheckBox3, new org.netbeans.lib.awtextra.AbsoluteConstraints(35, 105, -1, -1));

        jCheckBox4.setText("Chicken Cheese Burger");
        jCheckBox4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jCheckBox4MouseClicked(evt);
            }
        });
        jCheckBox4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox4ActionPerformed(evt);
            }
        });
        BurgerBoder.add(jCheckBox4, new org.netbeans.lib.awtextra.AbsoluteConstraints(35, 133, -1, -1));

        jCheckBox5.setText("Creamy Mushroom Burger");
        jCheckBox5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jCheckBox5MouseClicked(evt);
            }
        });
        jCheckBox5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox5ActionPerformed(evt);
            }
        });
        BurgerBoder.add(jCheckBox5, new org.netbeans.lib.awtextra.AbsoluteConstraints(35, 161, -1, -1));

        jCheckBox6.setText("Grilled - Prawn Burger");
        jCheckBox6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jCheckBox6MouseClicked(evt);
            }
        });
        jCheckBox6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox6ActionPerformed(evt);
            }
        });
        BurgerBoder.add(jCheckBox6, new org.netbeans.lib.awtextra.AbsoluteConstraints(35, 189, -1, -1));

        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("-");
        jLabel14.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabel14.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel14MouseClicked(evt);
            }
        });
        BurgerBoder.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 190, 14, 22));

        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("-");
        jLabel12.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabel12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel12MouseClicked(evt);
            }
        });
        BurgerBoder.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 160, 14, 22));

        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("-");
        jLabel10.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabel10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel10MouseClicked(evt);
            }
        });
        BurgerBoder.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 130, 14, 22));

        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("-");
        jLabel8.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel8MouseClicked(evt);
            }
        });
        BurgerBoder.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 100, 14, 22));

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("-");
        jLabel6.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
        });
        BurgerBoder.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 70, 14, 22));

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("-");
        jLabel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        BurgerBoder.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 40, 14, 22));

        jTextField1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField1.setText("00");
        BurgerBoder.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 40, 40, -1));

        jTextField2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField2.setText("00");
        BurgerBoder.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 70, 40, -1));

        jTextField3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField3.setText("00");
        BurgerBoder.add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 100, 40, -1));

        jTextField4.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField4.setText("00");
        BurgerBoder.add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 130, 40, -1));

        jTextField5.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField5.setText("00");
        BurgerBoder.add(jTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(219, 161, 40, -1));

        jTextField6.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField6.setText("00");
        BurgerBoder.add(jTextField6, new org.netbeans.lib.awtextra.AbsoluteConstraints(219, 189, 40, -1));

        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText("+");
        jLabel15.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabel15.setPreferredSize(new java.awt.Dimension(8, 16));
        jLabel15.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel15MouseClicked(evt);
            }
        });
        BurgerBoder.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 190, 14, 22));

        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("+");
        jLabel13.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabel13.setPreferredSize(new java.awt.Dimension(8, 16));
        jLabel13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel13MouseClicked(evt);
            }
        });
        BurgerBoder.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 160, 14, 22));

        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("+");
        jLabel11.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabel11.setPreferredSize(new java.awt.Dimension(8, 16));
        jLabel11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel11MouseClicked(evt);
            }
        });
        BurgerBoder.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 130, 14, 22));

        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("+");
        jLabel9.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabel9.setPreferredSize(new java.awt.Dimension(8, 16));
        jLabel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel9MouseClicked(evt);
            }
        });
        BurgerBoder.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 100, 14, 22));

        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("+");
        jLabel7.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabel7.setPreferredSize(new java.awt.Dimension(8, 16));
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel7MouseClicked(evt);
            }
        });
        BurgerBoder.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 70, 14, 22));

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("+");
        jLabel5.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabel5.setPreferredSize(new java.awt.Dimension(8, 16));
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });
        BurgerBoder.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 40, 14, 22));

        burgerBoder.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        burgerBoder.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "BURGERS", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Segoe UI", 1, 18))); // NOI18N
        BurgerBoder.add(burgerBoder, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 290, 230));

        jPanel1.add(BurgerBoder, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, 320, 240));

        AppetizerBoder.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jCheckBox7.setText("French Fries");
        jCheckBox7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox7ActionPerformed(evt);
            }
        });
        AppetizerBoder.add(jCheckBox7, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 63, -1, -1));

        jCheckBox8.setText("Chicken Wings");
        jCheckBox8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox8ActionPerformed(evt);
            }
        });
        AppetizerBoder.add(jCheckBox8, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 91, -1, -1));

        jCheckBox9.setText("Cheese Garlic Bread");
        jCheckBox9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox9ActionPerformed(evt);
            }
        });
        AppetizerBoder.add(jCheckBox9, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 119, -1, -1));

        jCheckBox10.setText("Onion Rings");
        jCheckBox10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox10ActionPerformed(evt);
            }
        });
        AppetizerBoder.add(jCheckBox10, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 147, -1, -1));

        jCheckBox11.setText("Cheese Sticks");
        jCheckBox11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox11ActionPerformed(evt);
            }
        });
        AppetizerBoder.add(jCheckBox11, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 175, -1, -1));

        jTextField18.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField18.setText("00");
        AppetizerBoder.add(jTextField18, new org.netbeans.lib.awtextra.AbsoluteConstraints(185, 174, 31, -1));

        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel18.setText("-");
        jLabel18.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabel18.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel18MouseClicked(evt);
            }
        });
        AppetizerBoder.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(165, 174, 14, 22));

        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel19.setText("-");
        jLabel19.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabel19.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel19MouseClicked(evt);
            }
        });
        AppetizerBoder.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(165, 146, 14, 22));

        jLabel20.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel20.setText("-");
        jLabel20.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabel20.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel20MouseClicked(evt);
            }
        });
        AppetizerBoder.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(165, 118, 14, 22));

        jLabel21.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel21.setText("-");
        jLabel21.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabel21.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel21MouseClicked(evt);
            }
        });
        AppetizerBoder.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(165, 90, 14, 22));

        jLabel22.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel22.setText("-");
        jLabel22.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabel22.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel22MouseClicked(evt);
            }
        });
        AppetizerBoder.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(165, 62, 14, 22));

        jTextField7.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField7.setText("00");
        jTextField7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField7ActionPerformed(evt);
            }
        });
        AppetizerBoder.add(jTextField7, new org.netbeans.lib.awtextra.AbsoluteConstraints(185, 62, 31, -1));

        jTextField8.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField8.setText("00");
        AppetizerBoder.add(jTextField8, new org.netbeans.lib.awtextra.AbsoluteConstraints(185, 90, 31, -1));

        jTextField9.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField9.setText("00");
        AppetizerBoder.add(jTextField9, new org.netbeans.lib.awtextra.AbsoluteConstraints(185, 118, 31, -1));

        jTextField10.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField10.setText("00");
        AppetizerBoder.add(jTextField10, new org.netbeans.lib.awtextra.AbsoluteConstraints(185, 146, 31, -1));

        jLabel24.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel24.setText("+");
        jLabel24.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabel24.setPreferredSize(new java.awt.Dimension(8, 16));
        AppetizerBoder.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(222, 174, 14, 22));

        jLabel25.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel25.setText("+");
        jLabel25.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabel25.setPreferredSize(new java.awt.Dimension(8, 16));
        AppetizerBoder.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(222, 146, 14, 22));

        jLabel26.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel26.setText("+");
        jLabel26.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabel26.setPreferredSize(new java.awt.Dimension(8, 16));
        AppetizerBoder.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(222, 118, 14, 22));

        jLabel27.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel27.setText("+");
        jLabel27.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabel27.setPreferredSize(new java.awt.Dimension(8, 16));
        AppetizerBoder.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(222, 90, 14, 22));

        jLabel28.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel28.setText("+");
        jLabel28.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabel28.setPreferredSize(new java.awt.Dimension(8, 16));
        AppetizerBoder.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(222, 62, 14, 22));

        jLabel16.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel16.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "APPETIZERS", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Segoe UI", 1, 18))); // NOI18N
        AppetizerBoder.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 270, 190));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(AppetizerBoder, javax.swing.GroupLayout.PREFERRED_SIZE, 337, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(239, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(0, 220, Short.MAX_VALUE)
                .addComponent(AppetizerBoder, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, 590, 440));

        jLabel44.setForeground(new java.awt.Color(246, 166, 0));
        jLabel44.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/wallpaperBlack3.jpg"))); // NOI18N
        jPanel1.add(jLabel44, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1080, 720));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jCheckBox22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox22ActionPerformed
        // TODO add your handling code here:
         double p=1;
            jTextField22.setText(Double.toString(p));
    }//GEN-LAST:event_jCheckBox22ActionPerformed

    private void jCheckBox21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox21ActionPerformed
        // TODO add your handling code here:
         double p=1;
            jTextField21.setText(Double.toString(p));
    }//GEN-LAST:event_jCheckBox21ActionPerformed

    private void jCheckBox20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox20ActionPerformed
        // TODO add your handling code here:
         double p=1;
            jTextField20.setText(Double.toString(p));
    }//GEN-LAST:event_jCheckBox20ActionPerformed

    private void jCheckBox19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox19ActionPerformed
        // TODO add your handling code here:
         double p=1;
            jTextField19.setText(Double.toString(p));
    }//GEN-LAST:event_jCheckBox19ActionPerformed

    private void jCheckBox16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox16ActionPerformed
        // TODO add your handling code here:
         double p=1;
            jTextField16.setText(Double.toString(p));
    }//GEN-LAST:event_jCheckBox16ActionPerformed

    private void jCheckBox15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox15ActionPerformed
        // TODO add your handling code here:
         double p=1;
            jTextField15.setText(Double.toString(p));
    }//GEN-LAST:event_jCheckBox15ActionPerformed

    private void jCheckBox14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox14ActionPerformed
        // TODO add your handling code here:
         double p=1;
            jTextField14.setText(Double.toString(p));
    }//GEN-LAST:event_jCheckBox14ActionPerformed

    private void jCheckBox13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox13ActionPerformed
        // TODO add your handling code here:
         double p=1;
            jTextField13.setText(Double.toString(p));
    }//GEN-LAST:event_jCheckBox13ActionPerformed

    private void jCheckBox11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox11ActionPerformed
        // TODO add your handling code here:
         double p=1;
            jTextField18.setText(Double.toString(p));
    }//GEN-LAST:event_jCheckBox11ActionPerformed

    private void jCheckBox10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox10ActionPerformed
        // TODO add your handling code here:
         double p=1;
            jTextField10.setText(Double.toString(p));
    }//GEN-LAST:event_jCheckBox10ActionPerformed

    private void jCheckBox9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox9ActionPerformed
        // TODO add your handling code here:
         double p=1;
            jTextField9.setText(Double.toString(p));
    }//GEN-LAST:event_jCheckBox9ActionPerformed

    private void jCheckBox8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox8ActionPerformed
        // TODO add your handling code here:
         double p=1;
            jTextField8.setText(Double.toString(p));
    }//GEN-LAST:event_jCheckBox8ActionPerformed

    private void jCheckBox7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox7ActionPerformed
        // TODO add your handling code here:
         double p=1;
            jTextField7.setText(Double.toString(p));
    }//GEN-LAST:event_jCheckBox7ActionPerformed

    private void jCheckBox6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox6ActionPerformed

    private void jCheckBox5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox5ActionPerformed

    private void jCheckBox4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox4ActionPerformed

    private void jCheckBox3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox3ActionPerformed

    private void jCheckBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox2ActionPerformed

    private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox1ActionPerformed
        // TODO add your handling code here:    
    }//GEN-LAST:event_jCheckBox1ActionPerformed

    private void grTotalMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_grTotalMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_grTotalMouseExited

    private void grTotalMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_grTotalMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_grTotalMouseEntered

    private void grTotalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_grTotalMouseClicked
        // TODO add your handling code here:
        Double grTotal=0.0;
        Double total=Double.parseDouble(jTextField23.getText());
        double x = Double.parseDouble(jTextField11.getText());
        grTotal=total-(total*x/100);
        jTextField17.setText(Double.toString(grTotal));
        grTotal=Double.parseDouble(jTextField17.getText());
        
        
        
        
        
        try
        {
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/mrburger", "root", "");
            DefaultTableModel t1=(DefaultTableModel) BILL_TABLE_.getModel();
            int q=1;
            int p=0;
            int amt;
            Object v="Chicken Burger";
            PreparedStatement ps = con.prepareStatement("select * from menu where Item_Name='"+v+"';");
            ResultSet rs = ps.executeQuery();
            while (rs.next())
            {
                Object row[]={rs.getString(1),rs.getString(2),rs.getString(3),q};
                t1.addRow(row);
            }
            int r=t1.getRowCount();
            for (int i=0;i<r;i++)
            {
              p=Integer.parseInt(""+t1.getValueAt(i,2));
              amt=p*q;
              t1.setValueAt(amt,i,4);
            }
        }
        catch(Exception e){
            System.out.println(e);
        }
        
        
        
        
        
        
        
        
        
        
        
        
        
    }//GEN-LAST:event_grTotalMouseClicked

    private void exitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitMouseClicked
        // TODO add your handling code here:
        Admin ad = new Admin();
        ad.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_exitMouseClicked

    private void exitMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_exitMouseEntered

    private void exitMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_exitMouseExited

    private void back2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_back2MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_back2MouseClicked

    private void back2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_back2MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_back2MouseEntered

    private void back2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_back2MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_back2MouseExited

    private void clearMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clearMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_clearMouseClicked

    private void clearMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clearMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_clearMouseEntered

    private void clearMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clearMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_clearMouseExited

    private void reset2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_reset2MouseClicked
       jCheckBox1.setSelected(false);
       jCheckBox2.setSelected(false);
       jCheckBox3.setSelected(false);
       jCheckBox4.setSelected(false);
       jCheckBox5.setSelected(false);
       jCheckBox6.setSelected(false);
       jCheckBox7.setSelected(false);
       jCheckBox8.setSelected(false);
       jCheckBox9.setSelected(false);
       jCheckBox10.setSelected(false);
       jCheckBox11.setSelected(false);
       jCheckBox13.setSelected(false);
       jCheckBox14.setSelected(false);
       jCheckBox15.setSelected(false);
       jCheckBox16.setSelected(false);
       jCheckBox19.setSelected(false);
       jCheckBox20.setSelected(false);
       jCheckBox21.setSelected(false);
       jCheckBox22.setSelected(false);
      
       jTextField1.setText("00");
       jTextField2.setText("00");
       jTextField3.setText("00");
       jTextField4.setText("00");
       jTextField5.setText("00");
       jTextField6.setText("00");
       jTextField7.setText("00");
       jTextField8.setText("00");
       jTextField9.setText("00");
       jTextField10.setText("00");
       jTextField13.setText("00");
       jTextField14.setText("00");
       jTextField15.setText("00");
       jTextField16.setText("00");
       jTextField18.setText("00");
       jTextField19.setText("00");
       jTextField20.setText("00");
       jTextField21.setText("00");
       jTextField23.setText(" ");
       jTextField11.setText("00");
       jTextField17.setText(" ");
       jTextField22.setText("00");
    
    }//GEN-LAST:event_reset2MouseClicked

    private void reset2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_reset2MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_reset2MouseEntered

    private void reset2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_reset2MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_reset2MouseExited

    private void totalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_totalMouseClicked
        // TODO add your handling code here:
        double total=0;
        String[] id = new String[19];
        int[] qn = new int[19];
        int i =0;
        if(jCheckBox1.isSelected()){
            int p;
            p=Integer.parseInt(jTextField1.getText());
            total=total+(500*p);
            qn[i]=p;
            id[i]="BUR001";
            i+=1;
        }
        if(jCheckBox2.isSelected()){
            int p;
            p=Integer.parseInt(jTextField2.getText());
            total=total+(500*p);
            qn[i]=p;
            id[i]="BUR002";
            i+=1;
        }
        if(jCheckBox3.isSelected()){
            int p;
            p=Integer.parseInt(jTextField3.getText());
            total=total+(500*p);
            qn[i]=p;
            id[i]="";
            i+=1;
        }
        if(jCheckBox4.isSelected()){
            int p;
            p=Integer.parseInt(jTextField4.getText());
            total=total+(500*p);
            qn[i]=p;
            id[i]="";
            i+=1;
        }
        if(jCheckBox5.isSelected()){
            int p;
            p=Integer.parseInt(jTextField5.getText());
            total=total+(500*p);
            qn[i]=p;
            id[i]="";
            i+=1;
        }
        if(jCheckBox6.isSelected()){
            double p;
            p=Double.parseDouble(jTextField6.getText());
            total=total+(500*p);
        }
        if(jCheckBox7.isSelected()){
            double p;
            p=Double.parseDouble(jTextField7.getText());
            total=total+(500*p);
        }
        if(jCheckBox8.isSelected()){
            double p;
            p=Double.parseDouble(jTextField8.getText());
            total=total+(250*p);
        }
        if(jCheckBox9.isSelected()){
            double p;
            p=Double.parseDouble(jTextField9.getText());
            total=total+(200*p);
        }
        if(jCheckBox10.isSelected()){
            double p;
            p=Double.parseDouble(jTextField10.getText());
            total=total+(100*p);
        }
        if(jCheckBox11.isSelected()){
            double p;
            p=Double.parseDouble(jTextField18.getText());
            total=total+(150*p);
        }
        if(jCheckBox13.isSelected()){
            double p;
            p=Double.parseDouble(jTextField13.getText());
            total=total+(550*p);            
        }
        if(jCheckBox14.isSelected()){
            double p;
            p=Double.parseDouble(jTextField14.getText());
            total=total+(200*p);
        }
        if(jCheckBox15.isSelected()){
            double p;
            p=Double.parseDouble(jTextField15.getText());
            total=total+(540*p);
        }
        if(jCheckBox16.isSelected()){
            double p;
            p=Double.parseDouble(jTextField16.getText());
            total=total+(740*p);
        }
        if(jCheckBox19.isSelected()){
            double p;
            p=Double.parseDouble(jTextField19.getText());
            total=total+(200*p);
        }
        if(jCheckBox20.isSelected()){
            double p;
            p=Double.parseDouble(jTextField20.getText());
            total=total+(250*p);
        }
        if(jCheckBox21.isSelected()){
            double p;
            p=Double.parseDouble(jTextField21.getText());
            total=total+(250*p);
        }
        if(jCheckBox22.isSelected()){
            double p;
            p=Double.parseDouble(jTextField22.getText());
            total=total+(150*p);
        }
        jTextField23.setText(Double.toString(total));
        total=Double.parseDouble(jTextField23.getText());
        
        try
        {
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/mrburger", "root", "");
            DefaultTableModel t1=(DefaultTableModel) BILL_TABLE_.getModel();
            int q=1;
            int p=0;
            int amt;
            int j=t1.getRowCount();
            for (j = 0; j < 10; j++) {
                Object oId = id[j];
                int oQn = qn[j];
                Object v="Chicken Burger";
                PreparedStatement ps = con.prepareStatement("select * from menu where Item_Name='"+v+"';");
                ResultSet rs = ps.executeQuery();  
                Object row[]={rs.getString(1),rs.getString(2),rs.getString(3),qn[j]};
                t1.addRow(row);
            }
            int r=t1.getRowCount();
            for (int k=0;i<r;k++)
            {
              p=Integer.parseInt(""+t1.getValueAt(i,2));
              amt=p*qn[k];
              t1.setValueAt(amt,i,4);
            }
        }
        catch(Exception e){
            System.out.println(e);
        }
        
    }//GEN-LAST:event_totalMouseClicked

    private void totalMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_totalMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_totalMouseEntered

    private void totalMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_totalMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_totalMouseExited

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        // TODO add your handling code here:
        double p;
        p=Double.parseDouble(jTextField1.getText());
        if (p !=0) {
            p-=1;
            jTextField1.setText(Double.toString(p));
        }
        
    }//GEN-LAST:event_jLabel2MouseClicked

    private void jCheckBox1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jCheckBox1MouseClicked
        // TODO add your handling code here:
        double p=1;
            jTextField1.setText(Double.toString(p));
    }//GEN-LAST:event_jCheckBox1MouseClicked

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
        double p;
        p=Double.parseDouble(jTextField2.getText());
        if (p !=0) {
            p-=1;
            jTextField2.setText(Double.toString(p));
        }

    }//GEN-LAST:event_jLabel6MouseClicked

    private void jLabel10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10MouseClicked
        double p;
        p=Double.parseDouble(jTextField4.getText());
        if (p !=0) {
            p-=1;
            jTextField4.setText(Double.toString(p));
        }
  
    }//GEN-LAST:event_jLabel10MouseClicked

    private void jLabel8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseClicked
        double p;
        p=Double.parseDouble(jTextField3.getText());
        if (p !=0) {
            p-=1;
            jTextField3.setText(Double.toString(p));
        }

    }//GEN-LAST:event_jLabel8MouseClicked

    private void jLabel12MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel12MouseClicked
        double p;
        p=Double.parseDouble(jTextField5.getText());
        if (p !=0) {
            p-=1;
            jTextField5.setText(Double.toString(p));
        }
 
    }//GEN-LAST:event_jLabel12MouseClicked

    private void jLabel14MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel14MouseClicked
        double p;
        p=Double.parseDouble(jTextField6.getText());
        if (p !=0) {
            p-=1;
            jTextField6.setText(Double.toString(p));
        }

    }//GEN-LAST:event_jLabel14MouseClicked

    private void jLabel22MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel22MouseClicked
        // TODO add your handling code h
        double p;
        p=Double.parseDouble(jTextField7.getText());
        if (p !=0) {
            p-=1;
            jTextField7.setText(Double.toString(p));
        }

    }//GEN-LAST:event_jLabel22MouseClicked

    private void jLabel21MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel21MouseClicked
        // TODO add your handling code here:
        double p;
        p=Double.parseDouble(jTextField8.getText());
        if (p !=0) {
            p-=1;
            jTextField8.setText(Double.toString(p));
        }

  
    }//GEN-LAST:event_jLabel21MouseClicked

    private void jLabel20MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel20MouseClicked
        // TODO add your handling code here:
        double p;
        p=Double.parseDouble(jTextField9.getText());
        if (p !=0) {
            p-=1;
            jTextField9.setText(Double.toString(p));
        }

       
    }//GEN-LAST:event_jLabel20MouseClicked

    private void jLabel19MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel19MouseClicked
        // TODO add your handli
        double p;
        p=Double.parseDouble(jTextField10.getText());
        if (p !=0) {
            p-=1;
            jTextField10.setText(Double.toString(p));
        }

    }//GEN-LAST:event_jLabel19MouseClicked

    private void jLabel18MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel18MouseClicked
        // TODO add your handling code here:
        double p;
        p=Double.parseDouble(jTextField18.getText());
        if (p !=0) {
            p-=1;
            jTextField18.setText(Double.toString(p));
        }

       
    }//GEN-LAST:event_jLabel18MouseClicked

    private void jLabel48MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel48MouseClicked
        double p;
        p=Double.parseDouble(jTextField19.getText());
        if (p !=0) {
            p-=1;
            jTextField19.setText(Double.toString(p));
        }

    }//GEN-LAST:event_jLabel48MouseClicked

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
        double p;
        p=Double.parseDouble(jTextField1.getText());
        if (p !=0) {
            p+=1;
            jTextField1.setText(Double.toString(p));
        }
    }//GEN-LAST:event_jLabel5MouseClicked

    private void jLabel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseClicked
        double p;
        p=Double.parseDouble(jTextField2.getText());
        if (p !=0) {
            p+=1;
            jTextField2.setText(Double.toString(p));
        }
    }//GEN-LAST:event_jLabel7MouseClicked

    private void jLabel9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseClicked
        double p;
        p=Double.parseDouble(jTextField3.getText());
        if (p !=0) {
            p+=1;
            jTextField3.setText(Double.toString(p));
        }
    }//GEN-LAST:event_jLabel9MouseClicked

    private void jLabel11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel11MouseClicked
        double p;
        p=Double.parseDouble(jTextField4.getText());
        if (p !=0) {
            p+=1;
            jTextField4.setText(Double.toString(p));
        }
    }//GEN-LAST:event_jLabel11MouseClicked

    private void jLabel13MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel13MouseClicked
        double p;
        p=Double.parseDouble(jTextField5.getText());
        if (p !=0) {
            p+=1;
            jTextField5.setText(Double.toString(p));
        }
    }//GEN-LAST:event_jLabel13MouseClicked

    private void jLabel15MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel15MouseClicked
        double p;
        p=Double.parseDouble(jTextField6.getText());
        if (p !=0) {
            p+=1;
            jTextField6.setText(Double.toString(p));
        }
    }//GEN-LAST:event_jLabel15MouseClicked

    private void jCheckBox2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jCheckBox2MouseClicked
        double p=1;
            jTextField2.setText(Double.toString(p));
    }//GEN-LAST:event_jCheckBox2MouseClicked

    private void jCheckBox3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jCheckBox3MouseClicked
        double p=1;
            jTextField3.setText(Double.toString(p));
    }//GEN-LAST:event_jCheckBox3MouseClicked

    private void jCheckBox4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jCheckBox4MouseClicked
        double p=1;
            jTextField4.setText(Double.toString(p));
    }//GEN-LAST:event_jCheckBox4MouseClicked

    private void jCheckBox5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jCheckBox5MouseClicked
        double p=1;
            jTextField5.setText(Double.toString(p));
    }//GEN-LAST:event_jCheckBox5MouseClicked

    private void jCheckBox6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jCheckBox6MouseClicked
        double p=1;
            jTextField6.setText(Double.toString(p));
    }//GEN-LAST:event_jCheckBox6MouseClicked

    private void jTextField7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField7ActionPerformed

    private void jLabel47MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel47MouseClicked
        // TODO add your handling code here:
        double p;
        p=Double.parseDouble(jTextField20.getText());
        if (p !=0) {
            p-=1;
            jTextField20.setText(Double.toString(p));
        }

    }//GEN-LAST:event_jLabel47MouseClicked

    private void jLabel46MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel46MouseClicked
        // TODO add your handling code here:
        double p;
        p=Double.parseDouble(jTextField21.getText());
        if (p !=0) {
            p-=1;
            jTextField21.setText(Double.toString(p));
        }

    }//GEN-LAST:event_jLabel46MouseClicked

    private void jLabel45MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel45MouseClicked
        // TODO add your handling code here:
        double p;
        p=Double.parseDouble(jTextField22.getText());
        if (p !=0) {
            p-=1;
            jTextField22.setText(Double.toString(p));
        }

    }//GEN-LAST:event_jLabel45MouseClicked

    private void jLabel35MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel35MouseClicked
        // TODO add your handling code here:
        double p;
        p=Double.parseDouble(jTextField13.getText());
        if (p !=0) {
            p-=1;
            jTextField13.setText(Double.toString(p));
        }

    }//GEN-LAST:event_jLabel35MouseClicked

    private void jLabel34MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel34MouseClicked
        // TODO add your handling code here:
        double p;
        p=Double.parseDouble(jTextField14.getText());
        if (p !=0) {
            p-=1;
            jTextField14.setText(Double.toString(p));
        }

    }//GEN-LAST:event_jLabel34MouseClicked

    private void jLabel33MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel33MouseClicked
        // TODO add your handling code here:
        double p;
        p=Double.parseDouble(jTextField15.getText());
        if (p !=0) {
            p-=1;
            jTextField15.setText(Double.toString(p));
        }

    }//GEN-LAST:event_jLabel33MouseClicked

    private void jLabel32MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel32MouseClicked
        // TODO add your handling code here:
        double p;
        p=Double.parseDouble(jTextField16.getText());
        if (p !=0) {
            p-=1;
            jTextField16.setText(Double.toString(p));
        }

    }//GEN-LAST:event_jLabel32MouseClicked

    public void setColor(JLabel p){
        p.setBackground(new Color(205,200,35));
    }
    public void resetColor(JLabel p1){
        p1.setBackground(new Color(0,0,225));
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Oders.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Oders.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Oders.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Oders.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Oders().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel AppetizerBoder;
    private javax.swing.JTable BILL_TABLE_;
    private javax.swing.JPanel BeveragesBoder;
    private javax.swing.JPanel BurgerBoder;
    private javax.swing.JPanel DessertBoder;
    private javax.swing.JLabel back2;
    private javax.swing.JLabel burgerBoder;
    private javax.swing.JLabel clear;
    private javax.swing.JLabel exit;
    private javax.swing.JLabel grTotal;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox10;
    private javax.swing.JCheckBox jCheckBox11;
    private javax.swing.JCheckBox jCheckBox13;
    private javax.swing.JCheckBox jCheckBox14;
    private javax.swing.JCheckBox jCheckBox15;
    private javax.swing.JCheckBox jCheckBox16;
    private javax.swing.JCheckBox jCheckBox19;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JCheckBox jCheckBox20;
    private javax.swing.JCheckBox jCheckBox21;
    private javax.swing.JCheckBox jCheckBox22;
    private javax.swing.JCheckBox jCheckBox3;
    private javax.swing.JCheckBox jCheckBox4;
    private javax.swing.JCheckBox jCheckBox5;
    private javax.swing.JCheckBox jCheckBox6;
    private javax.swing.JCheckBox jCheckBox7;
    private javax.swing.JCheckBox jCheckBox8;
    private javax.swing.JCheckBox jCheckBox9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel53;
    private javax.swing.JLabel jLabel54;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField12;
    private javax.swing.JTextField jTextField13;
    private javax.swing.JTextField jTextField14;
    private javax.swing.JTextField jTextField15;
    private javax.swing.JTextField jTextField16;
    private javax.swing.JTextField jTextField17;
    private javax.swing.JTextField jTextField18;
    private javax.swing.JTextField jTextField19;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField20;
    private javax.swing.JTextField jTextField21;
    private javax.swing.JTextField jTextField22;
    private javax.swing.JTextField jTextField23;
    private javax.swing.JTextField jTextField24;
    private javax.swing.JTextField jTextField25;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    private javax.swing.JLabel reset2;
    private javax.swing.JLabel total;
    // End of variables declaration//GEN-END:variables
}
